import type { StoryManifestV1 } from '../domain/types';
import { storyManifestV1Schema } from '../domain/schemas';

const retrievedAt = '2026-07-17';

export const fengyunAsatStory: StoryManifestV1 = storyManifestV1Schema.parse({
  schemaVersion: 1,
  id: 'fengyun-asat',
  title: 'The other debris cloud',
  dek: 'A deliberate 2007 intercept produced the largest breakup in spaceflight history — and much of its cloud remains.',
  reconstructionPolicy: 'sourced-reconstruction',
  sources: [
    {
      id: 'esa-debris-faq',
      title: 'Space Debris FAQ: Frequently asked questions',
      url: 'https://www.esa.int/Space_Safety/Space_Debris/Space_Debris_FAQ_Frequently_asked_questions',
      retrievedAt,
      publisher: 'European Space Agency',
    },
    {
      id: 'nasa-radar-2025',
      title: 'Orbital Debris Radar Observations',
      url: 'https://ntrs.nasa.gov/api/citations/20250002783/downloads/ECSD2025_Radar_Obs_Manis_Presentation.pdf',
      retrievedAt,
      publisher: 'National Aeronautics and Space Administration',
    },
    {
      id: 'celestrak-current',
      title: 'Current GP Element Sets',
      url: 'https://celestrak.org/NORAD/elements/',
      retrievedAt,
      publisher: 'CelesTrak',
    },
    {
      id: 'celestrak-gp-docs',
      title: 'A New Way to Obtain GP Data',
      url: 'https://celestrak.org/NORAD/documentation/gp-data-formats.php',
      retrievedAt,
      publisher: 'CelesTrak',
    },
  ],
  facts: [
    {
      id: 'fy-intercept',
      text: 'On 11 January 2007, China intercepted Fengyun-1C with a surface-launched medium-range missile at 862 km in a near-polar orbit.',
      sourceIds: ['esa-debris-faq'],
    },
    {
      id: 'fy-catalog-impact',
      text: 'The event added more than 3,300 trackable objects to the US Space Surveillance Network catalogue, increasing its size by 25 percent.',
      sourceIds: ['esa-debris-faq'],
    },
    {
      id: 'fy-largest',
      text: 'NASA describes Fengyun-1C as the largest breakup in the history of spaceflight.',
      sourceIds: ['nasa-radar-2025'],
    },
    {
      id: 'fy-remaining-2025',
      text: 'NASA reported 3,532 cataloged fragments and 2,557 still on orbit — 72 percent — on 3 January 2025.',
      sourceIds: ['nasa-radar-2025'],
      caveat: 'These figures are a dated global-catalog assessment. Counts change through cataloging and decay, and the installed SatGlobe snapshot is not the complete population.',
    },
    {
      id: 'fy-long-lived',
      text: 'ESA says the high event altitude and low ambient air density give the fragments long orbital lifetimes.',
      sourceIds: ['esa-debris-faq'],
    },
    {
      id: 'collision-comparison',
      text: 'NASA’s 3 January 2025 table lists 1,715 cataloged Cosmos 2251 fragments and 657 Iridium 33 fragments from the 2009 collision.',
      sourceIds: ['nasa-radar-2025'],
      caveat: 'The cited counts are the catalog totals reported for 3 January 2025, not the counts in this installed snapshot.',
    },
    {
      id: 'gp-elements',
      text: 'Public GP orbital data are fitted from Space Surveillance Network observations to produce mean elements for use with the SGP4 propagator.',
      sourceIds: ['celestrak-current', 'celestrak-gp-docs'],
      caveat: 'Element age varies across the installed debris records; propagation does not recreate the fragment cloud at the moment of the 2007 intercept.',
    },
  ],
  beats: [
    {
      id: 'the-intercept',
      eyebrow: '01 / ONE SATELLITE, THEN AN INTERCEPT',
      title: 'An intercept at 862 kilometers',
      dateLabel: '11 Jan 2007',
      narration: 'Fengyun-1C began as one weather satellite. A surface-launched missile then intercepted it where thin air removes debris only slowly; the parent and fragments now in view are today’s catalog identities, not a frame frozen at impact.',
      factIds: ['fy-intercept', 'fy-long-lived', 'gp-elements'],
      durationMs: 12_000,
      camera: { pitch: 0.7, yaw: 1.2, zoom: 0.52 },
      encoding: 'object-type',
      constellation: 'fengyun 1c',
      filterOverrides: { objectKinds: ['payload', 'debris'], status: 'all', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'largest-cloud',
      eyebrow: '02 / THE LARGEST BREAKUP',
      title: 'One event expands the catalog by a quarter',
      dateLabel: 'After the intercept',
      narration: 'Thousands of trackable fragments changed the low-orbit environment in one event. Their present spread illustrates the persistence of the breakup, not the cloud’s immediate 2007 shape.',
      factIds: ['fy-catalog-impact', 'fy-largest', 'fy-long-lived'],
      durationMs: 14_000,
      camera: { pitch: 0.55, yaw: 1.9, zoom: 0.55 },
      encoding: 'orbital-plane',
      constellation: 'fengyun 1c',
      filterOverrides: { objectKinds: ['debris'], status: 'all', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'second-cloud',
      eyebrow: '03 / TWO EVENTS, DIFFERENT CAUSES',
      title: 'One half of the later collision cloud',
      dateLabel: '10 Feb 2009',
      narration: 'This view isolates only the Cosmos 2251 fragments as a representative half of the 2009 collision population. The cited NASA table compares the catalog totals for both Cosmos 2251 and Iridium 33; the next story follows that accidental collision in full.',
      factIds: ['collision-comparison'],
      durationMs: 13_000,
      camera: { pitch: 0.4, yaw: 2.5, zoom: 0.55 },
      encoding: 'orbital-plane',
      constellation: 'cosmos 2251',
      filterOverrides: { objectKinds: ['debris'], status: 'all', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'fy-today',
      eyebrow: '04 / THE INSTALLED CATALOG',
      title: 'Still a present-tense population',
      dateLabel: 'Current snapshot',
      narration: 'The final view returns to the Fengyun fragments in this installation. Color now reports the freshness of each public element set — not the age of the fragment — and the visible subset is not a complete census.',
      factIds: ['fy-remaining-2025', 'gp-elements'],
      durationMs: 15_000,
      camera: { pitch: 0.3, yaw: 3.1, zoom: 0.62 },
      encoding: 'data-age',
      constellation: 'fengyun 1c',
      filterOverrides: { objectKinds: ['debris'], status: 'all', regimes: ['leo'] },
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
  ],
});
