import type { StoryManifestV1 } from '../domain/types';
import { storyManifestV1Schema } from '../domain/schemas';

const retrievedAt = '2026-07-18';

export const gnssFamiliesStory: StoryManifestV1 = storyManifestV1Schema.parse({
  schemaVersion: 1,
  id: 'gnss-families',
  title: 'Four constellations, four geometries',
  dek: 'A catalog-side comparison of GPS, GLONASS, Galileo, and BeiDou reveals four distinct orbital architectures.',
  reconstructionPolicy: 'sourced-reconstruction',
  sources: [
    {
      id: 'gps-space-segment',
      title: 'Space Segment',
      url: 'https://www.gps.gov/space-segment',
      retrievedAt,
      publisher: 'U.S. National Coordination Office for Space-Based Positioning, Navigation, and Timing',
    },
    {
      id: 'federal-space-agency-glonass',
      title: 'The Interoperable Global Navigation Satellite Systems Space Service Volume, Second Edition',
      url: 'https://www.unoosa.org/res/oosadoc/data/documents/2021/stspace/stspace75rev_1_0_html/st_space_75rev01E.pdf',
      retrievedAt: '2026-07-23',
      publisher: 'United Nations Office for Outer Space Affairs',
    },
    {
      id: 'gsc-galileo-system',
      title: 'System',
      url: 'https://www.gsc-europa.eu/galileo/system',
      retrievedAt,
      publisher: 'European GNSS Service Centre',
    },
    {
      id: 'china-beidou-white-paper',
      title: 'China\'s BeiDou Navigation Satellite System in the New Era',
      url: 'https://english.www.gov.cn/atts/stream/files/63647c05c6d028997c37caa7',
      retrievedAt,
      publisher: 'State Council Information Office of the People\'s Republic of China',
    },
    {
      id: 'celestrak-gp-docs',
      title: 'A New Way to Obtain GP Data',
      url: 'https://celestrak.org/NORAD/documentation/gp-data-formats.php',
      retrievedAt,
      publisher: 'CelesTrak',
    },
  ],
  facts: [
    {
      id: 'gps-architecture',
      text: 'The GPS baseline uses 24 slots in six equally spaced orbital planes at about 20,200 km altitude; each satellite circles Earth twice a day.',
      sourceIds: ['gps-space-segment'],
    },
    {
      id: 'glonass-architecture',
      text: 'The nominal GLONASS constellation uses 24 satellites in three roughly circular planes at 64.8 degrees inclination and about 19,100 km altitude.',
      sourceIds: ['federal-space-agency-glonass'],
    },
    {
      id: 'galileo-architecture',
      text: 'The Galileo baseline is a 24-satellite Medium Earth Orbit constellation arranged in three planes at 56 degrees inclination.',
      sourceIds: ['gsc-galileo-system'],
    },
    {
      id: 'beidou-architecture',
      text: 'BeiDou-3 completed deployment of a hybrid constellation of 24 MEO satellites, three inclined geosynchronous satellites, and three geostationary satellites in June 2020.',
      sourceIds: ['china-beidou-white-paper'],
    },
    {
      id: 'gp-elements',
      text: 'Public GP orbital data are fitted from Space Surveillance Network observations to produce mean elements for use with the SGP4 propagator.',
      sourceIds: ['celestrak-gp-docs'],
      caveat: 'These predicted paths do not establish signal health, user accuracy, or an operator\'s live service status.',
    },
  ],
  beats: [
    {
      id: 'four-families',
      eyebrow: '01 / ONE PURPOSE, DIFFERENT ORBITS',
      title: 'Start with four representative paths',
      dateLabel: 'Installed catalog comparison',
      narration: 'Against the wider active-payload MEO background, four drawn paths identify one installed representative each for GPS, GLONASS, Galileo, and BeiDou. They introduce the comparison; they are not a performance ranking or a complete count of any constellation.',
      factIds: ['gps-architecture', 'glonass-architecture', 'galileo-architecture', 'beidou-architecture', 'gp-elements'],
      durationMs: 13_000,
      camera: { pitch: 0.34, yaw: 0.38, zoom: 0.62 },
      encoding: 'orbit-regime',
      orbitCatalogIds: ['64202', '65590', '67160', '61187'],
      filterOverrides: { objectKinds: ['payload'], status: 'active', regimes: ['meo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'gps-six-planes',
      eyebrow: '02 / GPS',
      title: 'Six planes at the twelve-hour rhythm',
      dateLabel: 'Nominal design, current paths',
      narration: 'The source defines six equally spaced GPS planes. Six representative active NAVSTAR paths from the installed catalog make that architecture legible; the current dots and paths illustrate the design but do not prove satellite health.',
      factIds: ['gps-architecture', 'gp-elements'],
      durationMs: 13_000,
      camera: { pitch: 0.5, yaw: 1.4, zoom: 0.6 },
      encoding: 'orbital-plane',
      constellation: 'navstar',
      orbitCatalogIds: ['64202', '67588', '55268', '68791', '40730', '62339'],
      filterOverrides: { objectKinds: ['payload'], status: 'active', regimes: ['meo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'glonass-three-planes',
      eyebrow: '03 / GLONASS',
      title: 'Three planes, steeper inclination',
      dateLabel: 'Nominal design, current paths',
      narration: 'GLONASS uses three nominal planes at a higher inclination than the other MEO families here. The three drawn paths are installed active representatives from the three present right-ascension clusters, not a claim that only three GLONASS satellites exist.',
      factIds: ['glonass-architecture', 'gp-elements'],
      durationMs: 13_000,
      camera: { pitch: 0.46, yaw: 2.05, zoom: 0.6 },
      encoding: 'orbital-plane',
      constellation: 'glonass',
      orbitCatalogIds: ['43508', '42939', '41330'],
      filterOverrides: { objectKinds: ['payload'], status: 'active', regimes: ['meo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'galileo-three-planes',
      eyebrow: '04 / GALILEO',
      title: 'Three planes, farther out',
      dateLabel: 'Nominal design, current paths',
      narration: 'Galileo also uses three nominal planes, but its installed paths sit above the GPS and GLONASS shells. One active representative from each present plane cluster traces the sourced geometry without turning public orbit data into a service-status display.',
      factIds: ['galileo-architecture', 'gp-elements'],
      durationMs: 13_000,
      camera: { pitch: 0.42, yaw: 2.68, zoom: 0.63 },
      encoding: 'orbital-plane',
      constellation: 'galileo',
      orbitCatalogIds: ['59598', '61182', '43564'],
      filterOverrides: { objectKinds: ['payload'], status: 'active', regimes: ['meo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'beidou-hybrid',
      eyebrow: '05 / BEIDOU',
      title: 'One family across three orbit types',
      dateLabel: 'Hybrid constellation',
      narration: 'BeiDou breaks the all-MEO pattern. These installed active paths represent MEO, inclined geosynchronous, and geostationary members. SatGlobe groups both synchronous paths in its GEO period bucket; their different inclinations remain visible in the paths themselves.',
      factIds: ['beidou-architecture', 'gp-elements'],
      durationMs: 14_000,
      camera: { pitch: 0.28, yaw: 3.22, zoom: 0.7 },
      encoding: 'orbit-regime',
      constellation: 'beidou',
      orbitCatalogIds: ['61186', '44337', '56564'],
      filterOverrides: { objectKinds: ['payload'], status: 'active' },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'families-present',
      eyebrow: '06 / THE INSTALLED CATALOG',
      title: 'Four predictions in the wider MEO layer',
      dateLabel: 'Current snapshot',
      narration: 'The final view returns to one active MEO representative per family. The four drawn paths come from the installed public GP snapshot; every other visible point is wider active-payload MEO context, and none of it is operator telemetry or a statement of navigation accuracy.',
      factIds: ['gps-architecture', 'glonass-architecture', 'galileo-architecture', 'beidou-architecture', 'gp-elements'],
      durationMs: 15_000,
      camera: { pitch: 0.34, yaw: 3.72, zoom: 0.62 },
      encoding: 'orbital-plane',
      orbitCatalogIds: ['64202', '65590', '67160', '61187'],
      filterOverrides: { objectKinds: ['payload'], status: 'active', regimes: ['meo'] },
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
  ],
});
