import type { StoryManifestV1 } from '../domain/types';
import { storyManifestV1Schema } from '../domain/schemas';

const retrievedAt = '2026-07-17';

export const gpsConstellationStory: StoryManifestV1 = storyManifestV1Schema.parse({
  schemaVersion: 1,
  id: 'gps-constellation',
  title: 'The clockwork constellation',
  dek: 'GPS as deliberate geometry: six planes of satellites arranged so several are always overhead, anywhere.',
  reconstructionPolicy: 'sourced-reconstruction',
  sources: [
    {
      id: 'esa-navipedia-gps',
      title: 'GPS Space Segment',
      url: 'https://gssc.esa.int/navipedia/index.php/GPS_Space_Segment',
      retrievedAt,
      publisher: 'ESA Navipedia',
    },
    {
      id: 'celestrak-gps',
      title: 'GP Element Sets: GPS Operational',
      url: 'https://celestrak.org/NORAD/elements/',
      retrievedAt,
      publisher: 'CelesTrak',
    },
  ],
  facts: [
    {
      id: 'baseline-slots',
      text: 'The GPS baseline constellation is a 24-slot arrangement, expanded to 27 slots in 2011, with spare satellites maintained on orbit.',
      sourceIds: ['esa-navipedia-gps'],
    },
    {
      id: 'six-planes',
      text: 'GPS satellites fly in six equally-spaced orbital planes inclined 55 degrees to the equator.',
      sourceIds: ['esa-navipedia-gps'],
    },
    {
      id: 'meo-altitude',
      text: 'The constellation orbits at about 20,200 km altitude with a period of roughly 11 hours 58 minutes — two orbits per sidereal day.',
      sourceIds: ['esa-navipedia-gps'],
    },
    {
      id: 'gps-elements-public',
      text: 'Positions shown here are propagated from the public GPS Operational element sets, not from the control segment.',
      sourceIds: ['celestrak-gps'],
      caveat: 'Element sets describe orbits for prediction; they do not convey satellite health or signal status.',
    },
  ],
  beats: [
    {
      id: 'the-middle-layer',
      eyebrow: '01 / THE NAVIGATION LAYER',
      title: 'A quiet middle altitude',
      dateLabel: 'Context view',
      narration: 'Between the crowded low orbits and the distant geostationary ring lies a quieter band. Navigation constellations live here, high enough that each satellite sees a third of the planet at once.',
      factIds: ['meo-altitude'],
      durationMs: 11_000,
      camera: { pitch: 0.3, yaw: 0.6, zoom: 0.72 },
      encoding: 'orbit-regime',
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'six-planes-beat',
      eyebrow: '02 / THE GEOMETRY',
      title: 'Six planes, deliberately spaced',
      dateLabel: 'Representative installed paths',
      narration: 'Isolate the active NAVSTAR records and add six representative paths from the installed catalog, one from each plane. Those paths make the sourced six-plane design legible; the dots alone do not prove which plane each satellite occupies.',
      factIds: ['six-planes', 'baseline-slots', 'gps-elements-public'],
      durationMs: 13_000,
      camera: { pitch: 0.5, yaw: 1.4, zoom: 0.6 },
      encoding: 'orbit-regime',
      constellation: 'navstar',
      orbitCatalogIds: ['64202', '67588', '55268', '68791', '40730', '62339'],
      filterOverrides: { regimes: ['meo'], status: 'active' },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'two-orbits-a-day',
      eyebrow: '03 / THE CLOCKWORK',
      title: 'Twice around per sidereal day',
      dateLabel: 'Orbital period',
      narration: 'The source gives the just-under-twelve-hour period. The single representative line is a static propagated path for current catalog object 64202; it illustrates the orbit but does not independently prove that period.',
      factIds: ['meo-altitude', 'baseline-slots', 'gps-elements-public'],
      durationMs: 12_000,
      camera: { pitch: 0.12, yaw: 2.2, zoom: 0.6 },
      encoding: 'orbit-regime',
      constellation: 'navstar',
      orbitCatalogId: '64202',
      filterOverrides: { regimes: ['meo'], status: 'active' },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'gps-present',
      eyebrow: '04 / THE INSTALLED CATALOG',
      title: 'The constellation as tracked today',
      dateLabel: 'Current snapshot',
      narration: 'The final view propagates the public element sets in the installed catalog. It shows where the constellation is — while satellite health, signal accuracy, and control-segment decisions live outside this picture.',
      factIds: ['gps-elements-public'],
      durationMs: 14_000,
      camera: { pitch: 0.34, yaw: 2.9, zoom: 0.6 },
      encoding: 'orbit-regime',
      constellation: 'navstar',
      filterOverrides: { regimes: ['meo'], status: 'active' },
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
  ],
});
