import type { StoryManifestV1 } from '../domain/types';
import { storyManifestV1Schema } from '../domain/schemas';

const retrievedAt = '2026-07-17';

export const issAssemblyStory: StoryManifestV1 = storyManifestV1Schema.parse({
  schemaVersion: 1,
  id: 'iss-assembly',
  title: 'A station, one launch at a time',
  dek: 'Forty-two assembly flights turned separately launched elements into one orbiting laboratory.',
  reconstructionPolicy: 'sourced-reconstruction',
  sources: [
    {
      id: 'nasa-iss-facts',
      title: 'International Space Station Facts and Figures',
      url: 'https://www.nasa.gov/international-space-station/space-station-facts-and-figures/',
      retrievedAt,
      publisher: 'National Aeronautics and Space Administration',
    },
    {
      id: 'esa-iss-building',
      title: 'Building the International Space Station',
      url: 'https://www.esa.int/Science_Exploration/Human_and_Robotic_Exploration/International_Space_Station/Building_the_International_Space_Station3',
      retrievedAt,
      publisher: 'European Space Agency',
    },
    {
      id: 'celestrak-gp-docs',
      title: 'A New Way to Obtain GP Data',
      url: 'https://celestrak.org/NORAD/documentation/gp-data-formats.php',
      retrievedAt,
      publisher: 'CelesTrak',
    },
  ],
  facts: [
    {
      id: 'assembly-piecewise',
      text: 'The International Space Station was assembled piece by piece at approximately 400 km altitude, requiring more than 40 missions.',
      sourceIds: ['esa-iss-building'],
    },
    {
      id: 'assembly-flights',
      text: 'NASA lists 42 assembly flights: 37 Space Shuttle flights and five Russian Proton or Soyuz rocket flights.',
      sourceIds: ['nasa-iss-facts'],
    },
    {
      id: 'first-pair',
      text: 'Zarya launched on 20 November 1998 aboard a Russian Proton rocket; Unity followed on 4 December aboard Space Shuttle Endeavour.',
      sourceIds: ['esa-iss-building'],
    },
    {
      id: 'later-modules',
      text: 'ESA’s assembly chronology lists Zvezda on 12 July 2000, Destiny on 7 February 2001, and Nauka on 21 July 2021.',
      sourceIds: ['esa-iss-building'],
    },
    {
      id: 'iss-rhythm',
      text: 'The station orbits Earth about every 90 minutes and makes 16 orbits in 24 hours.',
      sourceIds: ['nasa-iss-facts'],
    },
    {
      id: 'gp-elements',
      text: 'Public GP orbital data are fitted from Space Surveillance Network observations to produce mean elements for use with the SGP4 propagator.',
      sourceIds: ['celestrak-gp-docs'],
      caveat: 'The installed module-labelled records share the station’s present orbit; they are not separate historical trajectories or a complete physical parts list.',
    },
  ],
  beats: [
    {
      id: 'assembly-context',
      eyebrow: '01 / TOO LARGE FOR ONE LAUNCH',
      title: 'Build it in orbit',
      dateLabel: 'Assembly context',
      narration: 'The station could not arrive as one finished object. It was carried up piece by piece, then joined in low Earth orbit over more than forty missions.',
      factIds: ['assembly-piecewise'],
      durationMs: 11_000,
      camera: { pitch: 0.26, yaw: 0.38, zoom: 0.62 },
      encoding: 'object-type',
      filterOverrides: { regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'zarya',
      eyebrow: '02 / THE FIRST ELEMENT',
      title: 'Zarya begins the station',
      dateLabel: '20 Nov 1998',
      narration: 'Zarya was the first element in orbit. This mark identifies that module in the installed catalog; its propagated position is present-day context, not a replay of launch day.',
      factIds: ['first-pair', 'gp-elements'],
      durationMs: 12_000,
      camera: { pitch: 0.08, yaw: 1.1, zoom: 0.43 },
      encoding: 'launch-cohort',
      constellation: 'iss (zarya)',
      orbitCatalogId: '25544',
      filterOverrides: { objectKinds: ['payload'], status: 'all', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'unity',
      eyebrow: '03 / THE FIRST CONNECTION',
      title: 'Unity follows',
      dateLabel: '4 Dec 1998',
      narration: 'Two weeks later, Unity arrived aboard Endeavour. Linking the first two elements turned separate launches into the beginning of an assembled station.',
      factIds: ['first-pair'],
      durationMs: 12_000,
      camera: { pitch: 0.08, yaw: 1.5, zoom: 0.43 },
      encoding: 'launch-cohort',
      constellation: 'iss (unity)',
      orbitCatalogId: '25575',
      filterOverrides: { objectKinds: ['payload'], status: 'all', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'assembly-arc',
      eyebrow: '04 / FORTY-TWO FLIGHTS',
      title: 'Five identities, one present orbit',
      dateLabel: '1998–2021 milestones',
      narration: 'Zarya, Unity, Zvezda, Destiny, and Nauka survive here as five module-labelled catalog identities. Their identical present orbit collapses to one mark: a chronology cue, not an animation of the station’s physical construction.',
      factIds: ['assembly-flights', 'later-modules', 'gp-elements'],
      durationMs: 14_000,
      camera: { pitch: 0.08, yaw: 1.1, zoom: 0.43 },
      encoding: 'object-type',
      constellation: 'iss (',
      orbitCatalogId: '25544',
      filterOverrides: { objectKinds: ['payload'], status: 'all', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'station-today',
      eyebrow: '05 / THE INSTALLED CATALOG',
      title: 'One station, sixteen circuits a day',
      dateLabel: 'Current snapshot',
      narration: 'The five module labels share one propagated station orbit and therefore one visible mark. The assembly story spans decades; the laboratory they identify now completes about sixteen circuits of Earth each day.',
      factIds: ['iss-rhythm', 'gp-elements'],
      durationMs: 15_000,
      camera: { pitch: 0.08, yaw: 1.1, zoom: 0.43 },
      encoding: 'object-type',
      constellation: 'iss (',
      orbitCatalogId: '25544',
      filterOverrides: { objectKinds: ['payload'], status: 'all', regimes: ['leo'] },
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
  ],
});
