import type { StoryManifestV1 } from '../domain/types';
import { storyManifestV1Schema } from '../domain/schemas';

const retrievedAt = '2026-07-18';

export const landsatContinuityStory: StoryManifestV1 = storyManifestV1Schema.parse({
  schemaVersion: 1,
  id: 'landsat-continuity',
  title: 'The long look at Earth',
  dek: 'Five Landsat milestones connect the program\'s 1972 beginning to today\'s paired land-imaging cadence.',
  reconstructionPolicy: 'sourced-reconstruction',
  sources: [
    {
      id: 'usgs-landsat-about',
      title: 'About Landsat Missions',
      url: 'https://www.usgs.gov/landsat-missions/about',
      retrievedAt,
      publisher: 'U.S. Geological Survey',
    },
    {
      id: 'usgs-landsat-1',
      title: 'Landsat 1',
      url: 'https://www.usgs.gov/landsat-missions/landsat-1',
      retrievedAt,
      publisher: 'U.S. Geological Survey',
    },
    {
      id: 'usgs-landsat-5',
      title: 'Landsat 5',
      url: 'https://www.usgs.gov/landsat-missions/landsat-5',
      retrievedAt,
      publisher: 'U.S. Geological Survey',
    },
    {
      id: 'usgs-landsat-7',
      title: 'Landsat 7',
      url: 'https://www.usgs.gov/landsat-missions/landsat-7',
      retrievedAt,
      publisher: 'U.S. Geological Survey',
    },
    {
      id: 'usgs-landsat-8',
      title: 'Landsat 8',
      url: 'https://www.usgs.gov/landsat-missions/landsat-8',
      retrievedAt,
      publisher: 'U.S. Geological Survey',
    },
    {
      id: 'nasa-landsat-9',
      title: 'Landsat 9 Mission Details',
      url: 'https://science.nasa.gov/mission/landsat-9/mission-details/',
      retrievedAt,
      publisher: 'National Aeronautics and Space Administration',
    },
    {
      id: 'usgs-landsat-acquisitions',
      title: 'Landsat Acquisitions',
      url: 'https://www.usgs.gov/landsat-missions/landsat-acquisitions',
      retrievedAt,
      publisher: 'U.S. Geological Survey',
    },
    {
      id: 'celestrak-gp-docs',
      title: 'A New Way to Obtain GP Data',
      url: 'https://celestrak.org/NORAD/documentation/gp-data-formats.php',
      retrievedAt,
      publisher: 'CelesTrak',
    },
  ],
  facts: [
    {
      id: 'landsat-record',
      text: 'Since 1972, the joint NASA and USGS Landsat program has repeatedly made moderate-scale multispectral observations of the global land surface.',
      sourceIds: ['usgs-landsat-about'],
    },
    {
      id: 'landsat-1-start',
      text: 'NASA launched the Earth Resources Technology Satellite on July 23, 1972; later renamed Landsat 1, it was the first satellite explicitly designed to study Earth.',
      sourceIds: ['usgs-landsat-1'],
    },
    {
      id: 'landsat-5-longevity',
      text: 'Landsat 5 launched on March 1, 1984, delivered Earth-imaging data for nearly 29 years, and was decommissioned on June 5, 2013.',
      sourceIds: ['usgs-landsat-5'],
    },
    {
      id: 'landsat-7-record',
      text: 'Landsat 7 launched on April 15, 1999, and was decommissioned on June 4, 2025; its 1999–2024 observations are preserved in the USGS archive.',
      sourceIds: ['usgs-landsat-7'],
    },
    {
      id: 'landsat-7-gaps',
      text: 'Since June 2003, Landsat 7 data have contained gaps caused by failure of the Enhanced Thematic Mapper Plus Scan Line Corrector.',
      sourceIds: ['usgs-landsat-7'],
    },
    {
      id: 'landsat-8-launch',
      text: 'Landsat 8 launched on February 11, 2013.',
      sourceIds: ['usgs-landsat-8'],
    },
    {
      id: 'landsat-9-launch',
      text: 'Landsat 9 launched on September 27, 2021.',
      sourceIds: ['nasa-landsat-9'],
    },
    {
      id: 'eight-day-offset',
      text: 'The Worldwide Reference System-2 has a 16-day repeat cycle per satellite, with Landsat 8 and Landsat 9 offset by eight days.',
      sourceIds: ['usgs-landsat-acquisitions'],
    },
    {
      id: 'gp-elements',
      text: 'Public GP orbital data are fitted from Space Surveillance Network observations to produce mean elements for use with the SGP4 propagator.',
      sourceIds: ['celestrak-gp-docs'],
      caveat: 'Orbit paths show predicted spacecraft position, not imagery, sensor condition, or a replay of a historical acquisition.',
    },
  ],
  beats: [
    {
      id: 'landsat-1-begins',
      eyebrow: '01 / THE FIRST LOOK',
      title: 'A new way to study Earth',
      dateLabel: '23 Jul 1972',
      narration: 'ERTS, later Landsat 1, began the record in 1972. The mark and path here come from its retained installed catalog record at the story\'s present simulation time—not from launch day. Data-age color describes only that public element set\'s epoch.',
      factIds: ['landsat-record', 'landsat-1-start', 'gp-elements'],
      durationMs: 13_000,
      camera: { pitch: 0.18, yaw: 0.7, zoom: 0.46 },
      encoding: 'data-age',
      constellation: 'landsat 1 (',
      orbitCatalogId: '6126',
      filterOverrides: { objectKinds: ['payload'], status: 'all', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'landsat-5-endures',
      eyebrow: '02 / THE LONG MIDDLE',
      title: 'A three-year design lasts nearly twenty-nine',
      dateLabel: '1984–2013',
      narration: 'Landsat 5 carried the record for nearly twenty-nine years. Its installed path is present-day propagated orbital context for the spacecraft, not a replay of any image or a claim that the mission remains active.',
      factIds: ['landsat-5-longevity', 'gp-elements'],
      durationMs: 13_000,
      camera: { pitch: 0.12, yaw: 1.32, zoom: 0.44 },
      encoding: 'data-age',
      constellation: 'landsat 5',
      orbitCatalogId: '14780',
      filterOverrides: { objectKinds: ['payload'], status: 'all', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'landsat-7-imperfect',
      eyebrow: '03 / CONTINUITY WITH GAPS',
      title: 'The orbit continues; the images change',
      dateLabel: '1999–2025',
      narration: 'Landsat 7 extended the archive, even after its 2003 Scan Line Corrector failure introduced image gaps. The orbital mark cannot show those gaps; that limitation belongs to the instrument data and is established by the source.',
      factIds: ['landsat-7-record', 'landsat-7-gaps', 'gp-elements'],
      durationMs: 13_000,
      camera: { pitch: 0.14, yaw: 1.95, zoom: 0.44 },
      encoding: 'data-age',
      constellation: 'landsat 7',
      orbitCatalogId: '25682',
      filterOverrides: { objectKinds: ['payload'], status: 'all', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'landsat-8-renews',
      eyebrow: '04 / A NEW GENERATION',
      title: 'Landsat 8 renews the record',
      dateLabel: '11 Feb 2013',
      narration: 'Landsat 8 arrived as Landsat 5 reached the end of its exceptionally long mission. This active installed record supplies current predicted orbital context; the launch date and continuity claim come from USGS, not from the dot itself.',
      factIds: ['landsat-record', 'landsat-5-longevity', 'landsat-8-launch', 'gp-elements'],
      durationMs: 13_000,
      camera: { pitch: 0.16, yaw: 2.58, zoom: 0.44 },
      encoding: 'data-age',
      constellation: 'landsat 8',
      orbitCatalogId: '39084',
      filterOverrides: { objectKinds: ['payload'], status: 'active', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'landsat-9-joins',
      eyebrow: '05 / THE PARTNER',
      title: 'Landsat 9 joins the cadence',
      dateLabel: '27 Sep 2021',
      narration: 'Landsat 9 joined Landsat 8 in the same land-imaging system. Its current predicted path is visible here; the sourced eight-day acquisition offset describes the pair\'s schedule and is not proved by a single static orbit line.',
      factIds: ['landsat-9-launch', 'eight-day-offset', 'gp-elements'],
      durationMs: 13_000,
      camera: { pitch: 0.16, yaw: 3.18, zoom: 0.44 },
      encoding: 'data-age',
      constellation: 'landsat 9',
      orbitCatalogId: '49260',
      filterOverrides: { objectKinds: ['payload'], status: 'active', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'landsat-pair-present',
      eyebrow: '06 / THE INSTALLED CATALOG',
      title: 'Two active records, one continuing archive',
      dateLabel: 'Current snapshot',
      narration: 'The active filter leaves Landsat 8 and Landsat 9, with both predicted paths drawn from the installed public GP snapshot. Older Landsat spacecraft remain cataloged but are hidden here; this view shows neither imagery nor mission telemetry.',
      factIds: ['landsat-record', 'landsat-8-launch', 'landsat-9-launch', 'eight-day-offset', 'gp-elements'],
      durationMs: 15_000,
      camera: { pitch: 0.2, yaw: 3.78, zoom: 0.47 },
      encoding: 'data-age',
      constellation: 'landsat',
      orbitCatalogIds: ['39084', '49260'],
      filterOverrides: { objectKinds: ['payload'], status: 'active', regimes: ['leo'] },
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
  ],
});
