import type { StoryManifestV1 } from '../domain/types';
import { storyManifestV1Schema } from '../domain/schemas';

const retrievedAt = '2026-07-17';

export const launchToOrbitStory: StoryManifestV1 = storyManifestV1Schema.parse({
  schemaVersion: 1,
  id: 'launch-to-orbit',
  title: 'From launch to orbit',
  dek: 'The catalog starts after liftoff: payloads separate, transfer, work, retire, and remain as orbital records.',
  reconstructionPolicy: 'sourced-reconstruction',
  sources: [
    {
      id: 'esa-orbit-types',
      title: 'Types of orbits',
      url: 'https://www.esa.int/Enabling_Support/Space_Transportation/Types_of_orbits',
      retrievedAt,
      publisher: 'European Space Agency',
    },
    {
      id: 'esa-mission-complete',
      title: 'What happens when a mission is complete?',
      url: 'https://www.esa.int/Science_Exploration/Space_Science/What_happens_when_a_mission_is_complete',
      retrievedAt,
      publisher: 'European Space Agency',
    },
    {
      id: 'esa-debris-faq',
      title: 'Space Debris FAQ: Frequently asked questions',
      url: 'https://www.esa.int/Space_Safety/Space_Debris/Space_Debris_FAQ_Frequently_asked_questions',
      retrievedAt,
      publisher: 'European Space Agency',
    },
    {
      id: 'celestrak-gp-docs',
      title: 'A New Way to Obtain GP Data',
      url: 'https://celestrak.org/NORAD/documentation/gp-data-formats.php',
      retrievedAt,
      publisher: 'CelesTrak',
    },
  ],
  facts: [
    {
      id: 'launcher-job',
      text: 'A launcher passes through the atmosphere and provides the horizontal velocity needed to enter orbit.',
      sourceIds: ['esa-orbit-types'],
    },
    {
      id: 'one-or-many',
      text: 'A launch mission can deliver one or more payloads into designated orbits.',
      sourceIds: ['esa-orbit-types'],
    },
    {
      id: 'launch-group',
      text: 'CelesTrak’s International Designator query returns the catalog objects associated with a particular launch.',
      sourceIds: ['celestrak-gp-docs'],
      caveat: 'The representative 2026-027 cohort is read from the installed snapshot; its membership can change when the catalog is refreshed.',
    },
    {
      id: 'transfer-orbit',
      text: 'Spacecraft are not always placed directly in their final orbit; onboard motors can move them from an initial transfer orbit to another orbit.',
      sourceIds: ['esa-orbit-types'],
    },
    {
      id: 'geo-arrival',
      text: 'A spacecraft in geostationary transfer orbit can fire its engines at 35,786 km apogee to circularize into geostationary orbit.',
      sourceIds: ['esa-orbit-types'],
    },
    {
      id: 'end-of-life',
      text: 'Low-Earth-orbit spacecraft can be lowered for atmospheric reentry, while high-altitude geosynchronous satellites are typically raised to graveyard orbits.',
      sourceIds: ['esa-mission-complete'],
    },
    {
      id: 'drag-decay',
      text: 'Atmospheric drag extracts orbital energy, lowers an object’s altitude, and eventually causes reentry.',
      sourceIds: ['esa-debris-faq'],
    },
    {
      id: 'gp-elements',
      text: 'Public GP orbital data are fitted from Space Surveillance Network observations to produce mean elements for use with the SGP4 propagator.',
      sourceIds: ['celestrak-gp-docs'],
      caveat: 'Current element sets do not provide one object’s historical ascent, maneuvers, operational intent, or complete lifecycle.',
    },
  ],
  beats: [
    {
      id: 'catalog-starts-after-launch',
      eyebrow: '01 / THE HORIZONTAL PUSH',
      title: 'The catalog begins after ascent',
      dateLabel: 'Representative installed cohort',
      narration: 'A rocket must first cross the atmosphere and build the sideways speed that makes orbit possible. SatGlobe begins after that climb, with independently catalogued objects from one representative launch.',
      factIds: ['launcher-job', 'launch-group'],
      durationMs: 11_000,
      camera: { pitch: 0.26, yaw: 0.38, zoom: 0.43 },
      encoding: 'launch-cohort',
      launchCohort: '2026-027',
      filterOverrides: { objectKinds: ['payload', 'rocket-body', 'debris'], status: 'all', regimes: ['leo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'one-launch-many-records',
      eyebrow: '02 / ONE LAUNCH, SEVERAL OBJECTS',
      title: 'The ride and debris remain catalogued',
      dateLabel: '1 rocket body · 1 debris record',
      narration: 'The installed 2026-027 cohort contains seven payloads, one rocket body, and one debris record. This chapter filters the scene to those two non-payload records. At planetary scale their enlarged marks can overlap or sit behind Earth, so the count comes from the installed catalog rather than visual identification; this is present membership, not the sequence or timing of separation.',
      factIds: ['one-or-many', 'launch-group', 'gp-elements'],
      durationMs: 12_000,
      camera: { pitch: 0.26, yaw: 0.38, zoom: 0.43 },
      encoding: 'object-type',
      launchCohort: '2026-027',
      filterOverrides: { objectKinds: ['rocket-body', 'debris'], status: 'all', regimes: ['leo'] },
      // Both records ride cohort-derived orbit lines; their marks alone can hide behind Earth.
      orbitMatchLimit: 2,
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'transfer-population',
      eyebrow: '03 / BETWEEN ORBITS',
      title: 'Some payloads take the long way up',
      dateLabel: 'Representative transfer population',
      narration: 'A transfer orbit is an intermediate path, often highly elliptical. This is a representative current population — not the history of the cohort in the previous chapter.',
      factIds: ['transfer-orbit', 'geo-arrival', 'gp-elements'],
      durationMs: 13_000,
      camera: { pitch: 0.55, yaw: 1.9, zoom: 0.72 },
      encoding: 'orbit-regime',
      filterOverrides: { regimes: ['heo'] },
      // The narration's "highly elliptical" claim needs visible ellipses, not dots.
      orbitMatchLimit: 4,
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'working-orbit',
      eyebrow: '04 / THE OPERATING LAYER',
      title: 'Circularize and begin the mission',
      dateLabel: 'Geostationary example',
      narration: 'For a geostationary mission, an engine burn at the transfer orbit’s high point can circularize the path into the distant equatorial ring. Other missions choose other working orbits.',
      factIds: ['geo-arrival'],
      durationMs: 13_000,
      camera: { pitch: 0.08, yaw: 1.3, zoom: 0.78 },
      encoding: 'orbit-regime',
      filterOverrides: { regimes: ['geo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'retirement',
      eyebrow: '05 / LEAVE THE WORKING ORBIT',
      title: 'Retirement is another maneuver',
      dateLabel: 'End-of-life strategies',
      narration: 'Low-orbit spacecraft can be lowered toward reentry; geosynchronous spacecraft are typically raised away from the protected ring. Inactive payloads and rocket bodies show why disposal remains part of mission design.',
      factIds: ['end-of-life', 'drag-decay'],
      durationMs: 13_000,
      camera: { pitch: 0.3, yaw: 2.5, zoom: 0.72 },
      encoding: 'object-type',
      filterOverrides: { objectKinds: ['payload', 'rocket-body'], status: 'inactive', regimes: ['leo', 'geo'] },
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'catalog-boundary',
      eyebrow: '06 / WHAT THIS SNAPSHOT KNOWS',
      title: 'A current record, not a flight recorder',
      dateLabel: 'Installed catalog',
      narration: 'Return to the representative cohort. Color now means element-set freshness, not vehicle age: the catalog can propagate current records, but it cannot replay ascent, maneuvers, or operator intent.',
      factIds: ['launch-group', 'gp-elements'],
      durationMs: 15_000,
      camera: { pitch: 0.34, yaw: 2.9, zoom: 0.45 },
      encoding: 'data-age',
      launchCohort: '2026-027',
      filterOverrides: { objectKinds: ['payload', 'rocket-body', 'debris'], status: 'all', regimes: ['leo'] },
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
  ],
});
