import type { StoryManifestV1 } from '../domain/types';
import { storyManifestV1Schema } from '../domain/schemas';

const retrievedAt = '2026-07-17';

export const oneDayInOrbitStory: StoryManifestV1 = storyManifestV1Schema.parse({
  schemaVersion: 1,
  id: 'one-day-in-orbit',
  title: 'The clock in the sky',
  dek: 'Twenty-four hours mean sixteen circuits in low orbit and just over one turn of the geostationary ring.',
  reconstructionPolicy: 'sourced-reconstruction',
  sources: [
    {
      id: 'nasa-iss-facts',
      title: 'International Space Station Facts and Figures',
      url: 'https://www.nasa.gov/international-space-station/space-station-facts-and-figures/',
      retrievedAt,
      publisher: 'National Aeronautics and Space Administration',
    },
    {
      id: 'esa-orbit-types',
      title: 'Types of orbits',
      url: 'https://www.esa.int/Enabling_Support/Space_Transportation/Types_of_orbits',
      retrievedAt,
      publisher: 'European Space Agency',
    },
    {
      id: 'celestrak-gp-docs',
      title: 'A New Way to Obtain GP Data',
      url: 'https://celestrak.org/NORAD/documentation/gp-data-formats.php',
      retrievedAt,
      publisher: 'CelesTrak',
    },
  ],
  facts: [
    {
      id: 'leo-clock',
      text: 'Satellites in low Earth orbit travel at approximately 7.8 km/s and complete an orbit in about 90 minutes; the ISS circles Earth roughly 16 times a day.',
      sourceIds: ['esa-orbit-types'],
    },
    {
      id: 'iss-sunrises',
      text: 'In 24 hours, the ISS makes 16 orbits and passes through 16 sunrises and sunsets.',
      sourceIds: ['nasa-iss-facts'],
    },
    {
      id: 'geo-clock',
      text: 'A geostationary satellite completes an orbit in 23 hours 56 minutes 4 seconds at 35,786 km, matching Earth’s rotation and appearing fixed over one spot.',
      sourceIds: ['esa-orbit-types'],
    },
    {
      id: 'gp-elements',
      text: 'Public GP orbital data are fitted from Space Surveillance Network observations to produce mean elements for use with the SGP4 propagator.',
      sourceIds: ['celestrak-gp-docs'],
      caveat: 'The time steps in this story are SGP4 projections from the installed elements, not live operator telemetry or archived observations.',
    },
  ],
  beats: [
    {
      id: 'hour-zero',
      eyebrow: '01 / HOUR 00',
      title: 'Start the orbital clock',
      dateLabel: 'Story entry time',
      narration: 'Take one installed catalog snapshot as the starting bell. Every later chapter is computed from that same fixed instant, so moving backward and forward through the story never compounds time.',
      factIds: ['gp-elements'],
      durationMs: 11_000,
      camera: { pitch: 0.3, yaw: 0.6, zoom: 0.72 },
      encoding: 'orbit-regime',
      simulationTimeOffsetHours: 0,
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
    {
      id: 'one-low-orbit',
      eyebrow: '02 / NINETY MINUTES',
      title: 'Low orbit comes around again',
      dateLabel: '+1.5 hours',
      narration: 'The ISS is the familiar ninety-minute clock, but a fixed camera cannot reliably follow its single mark. This wider active-payload view shows the low-orbit regime after roughly one circuit while Earth turns beneath it.',
      factIds: ['leo-clock', 'iss-sunrises'],
      durationMs: 12_000,
      camera: { pitch: 0.08, yaw: 1.1, zoom: 0.44 },
      encoding: 'orbit-regime',
      filterOverrides: { regimes: ['leo'] },
      simulationTimeOffsetHours: 1.5,
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'six-hours',
      eyebrow: '03 / SIX HOURS',
      title: 'About four circuits later',
      dateLabel: '+6 hours',
      narration: 'A quarter of a day is roughly four low-orbit circuits. Across the wider population, many planes cross the moving boundary between sunlight and night.',
      factIds: ['leo-clock', 'iss-sunrises'],
      durationMs: 12_000,
      camera: { pitch: 0.44, yaw: 2.35, zoom: 0.5 },
      encoding: 'orbital-plane',
      filterOverrides: { regimes: ['leo'] },
      simulationTimeOffsetHours: 6,
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'half-day-geo',
      eyebrow: '04 / THE SLOW CLOCK',
      title: 'Halfway around the geostationary day',
      dateLabel: '+12 hours',
      narration: 'Farther out, the geostationary ring keeps pace with the rotating planet. Twelve hours changes its orientation in space while each satellite remains nearly fixed over its place on Earth.',
      factIds: ['geo-clock'],
      durationMs: 13_000,
      camera: { pitch: 0.08, yaw: 1.3, zoom: 0.78 },
      encoding: 'orbit-regime',
      filterOverrides: { regimes: ['geo'] },
      simulationTimeOffsetHours: 12,
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'hour-twenty-four',
      eyebrow: '05 / HOUR 24',
      title: 'One day, many orbital clocks',
      dateLabel: '+24 hours',
      narration: 'Return to the opening camera one projected day later. Low-orbit traffic has raced around the planet many times; a geostationary satellite has completed just over one inertial orbit while remaining fixed over Earth.',
      factIds: ['leo-clock', 'geo-clock', 'gp-elements'],
      durationMs: 15_000,
      camera: { pitch: 0.3, yaw: 0.6, zoom: 0.72 },
      encoding: 'orbit-regime',
      simulationTimeOffsetHours: 24,
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'return-to-anchor',
      eyebrow: '06 / THE INSTALLED CATALOG',
      title: 'Back to the starting instant',
      dateLabel: 'Story entry time',
      narration: 'The final chapter returns to the unchanged entry-time anchor. This is the same installed-catalog projection shown at entry; the intervening clocks were projections from its public element sets.',
      factIds: ['gp-elements'],
      durationMs: 12_000,
      camera: { pitch: 0.3, yaw: 0.6, zoom: 0.72 },
      encoding: 'orbit-regime',
      simulationTimeOffsetHours: 0,
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
  ],
});
