import type { StoryManifestV1 } from '../domain/types';
import { storyManifestV1Schema } from '../domain/schemas';

const retrievedAt = '2026-07-15';

export const starlinkBuildoutStory: StoryManifestV1 = storyManifestV1Schema.parse({
  schemaVersion: 1,
  id: 'starlink-buildout',
  title: 'Building a shell',
  dek: 'How repeated launches become an orbital constellation — and what the picture can and cannot tell us.',
  reconstructionPolicy: 'sourced-reconstruction',
  sources: [
    {
      id: 'spacex-starlink',
      title: 'Starlink',
      url: 'https://www.spacex.com/starlink',
      retrievedAt,
      publisher: 'SpaceX',
    },
    {
      id: 'spacex-sl21',
      title: 'Starlink mission',
      url: 'https://www.spacex.com/launches/sl-21',
      retrievedAt,
      publisher: 'SpaceX',
    },
    {
      id: 'fcc-gen2',
      title: 'SpaceX Gen2 Starlink Order and Authorization',
      url: 'https://docs.fcc.gov/public/attachments/DA-26-36A1.pdf',
      retrievedAt,
      publisher: 'Federal Communications Commission',
    },
    {
      id: 'fcc-transition',
      title: 'SpaceX request for orbital deployment and transition operations',
      url: 'https://docs.fcc.gov/public/attachments/DA-24-1193A1.pdf',
      retrievedAt,
      publisher: 'Federal Communications Commission',
    },
    {
      id: 'celestrak-supgp',
      title: 'Supplemental GP Data',
      url: 'https://celestrak.org/NORAD/elements/supplemental/',
      retrievedAt,
      publisher: 'CelesTrak',
    },
  ],
  facts: [
    {
      id: 'constellations-need-repetition',
      text: 'A constellation emerges from repeated deployments into coordinated orbital planes rather than from one launch.',
      sourceIds: ['fcc-gen2'],
    },
    {
      id: 'sixty-satellites',
      text: 'The March 14, 2021 Starlink mission deployed 60 satellites from a Falcon 9 launch.',
      sourceIds: ['spacex-sl21'],
    },
    {
      id: 'transition-orbits',
      text: 'Spacecraft may spend time in deployment and orbit-raising phases before entering an operational shell.',
      sourceIds: ['fcc-transition'],
    },
    {
      id: 'communications-purpose',
      text: 'Starlink is designed as a satellite internet constellation.',
      sourceIds: ['spacex-starlink', 'fcc-gen2'],
    },
    {
      id: 'gp-is-prediction',
      text: 'The scene propagates public general-perturbations element sets; it is not live operator telemetry.',
      sourceIds: ['celestrak-supgp'],
      caveat: 'Propagated locations become less representative as element sets age and after unmodeled maneuvers.',
    },
  ],
  beats: [
    {
      id: 'before-the-shell',
      eyebrow: '01 / THE ORBITAL ENVIRONMENT',
      title: 'Before the shell',
      dateLabel: 'Context view',
      narration: 'Begin with Earth orbit as an environment, not an empty stage. Payloads, rocket bodies, and debris already occupy distinct regimes; the restrained marks preserve that context.',
      factIds: ['constellations-need-repetition'],
      durationMs: 11_000,
      camera: { pitch: 0.26, yaw: 0.38, zoom: 0.62 },
      encoding: 'orbit-regime',
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'deployment-train',
      eyebrow: '02 / ONE LAUNCH COHORT',
      title: 'One launch, one catalog cohort',
      dateLabel: '2021-021 in the installed catalog',
      narration: 'The March 14 mission began with 60 satellites. This view isolates its surviving installed records by International Designator; their current positions no longer recreate the temporary deployment train.',
      factIds: ['sixty-satellites', 'gp-is-prediction'],
      durationMs: 12_000,
      camera: { pitch: 0.08, yaw: 1.1, zoom: 0.52 },
      encoding: 'launch-cohort',
      constellation: 'starlink',
      launchCohort: '2021-021',
      // One cohort-derived path anchors the sparse marks to their shared shell.
      orbitMatchLimit: 1,
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
    {
      id: 'orbit-raising',
      eyebrow: '03 / THE MISSING CLIMB',
      title: 'The catalog cannot replay the climb',
      dateLabel: 'Present-day element sets',
      narration: 'Spacecraft can spend time raising and reshaping their orbits after separation. These current records can be propagated forward, but they cannot distinguish that earlier climb from later reassignment, maneuvering, or disposal.',
      factIds: ['transition-orbits', 'gp-is-prediction'],
      durationMs: 13_000,
      camera: { pitch: -0.18, yaw: 1.7, zoom: 0.48 },
      encoding: 'data-age',
      constellation: 'starlink',
      launchCohort: '2021-021',
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
    {
      id: 'building-planes',
      eyebrow: '04 / BUILDING THE SHELL',
      title: 'Repetition becomes geometry',
      dateLabel: 'Current 2021-launched subset',
      narration: 'Repeated launches fill orbital planes. This current surviving subset of Starlink records launched in 2021 makes that geometry legible without pretending to replay the year’s deployment sequence.',
      factIds: ['constellations-need-repetition'],
      durationMs: 14_000,
      camera: { pitch: 0.44, yaw: 2.35, zoom: 0.5 },
      encoding: 'orbital-plane',
      constellation: 'starlink',
      launchCohort: '2021-',
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
    {
      id: 'present-scale',
      eyebrow: '05 / THE INSTALLED CATALOG',
      title: 'The installed constellation at scale',
      dateLabel: 'Current snapshot',
      narration: 'The final view uses the full installed Starlink subset. Color reports GP element freshness, while coverage, maneuver intent, and operational health still require sources beyond this propagated picture.',
      factIds: ['communications-purpose', 'gp-is-prediction'],
      durationMs: 16_000,
      camera: { pitch: 0.34, yaw: 2.9, zoom: 0.5 },
      encoding: 'data-age',
      constellation: 'starlink',
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
  ],
});
