import type { StoryManifestV1 } from '../domain/types';
import { storyManifestV1Schema } from '../domain/schemas';

const retrievedAt = '2026-07-15';

export const starlinkBuildoutStory: StoryManifestV1 = storyManifestV1Schema.parse({
  schemaVersion: 1,
  id: 'starlink-buildout',
  title: 'Building a shell',
  dek: 'How repeated launches become an orbital constellation — and what the picture can and cannot tell us.',
  reconstructionPolicy: 'sourced-reconstruction',
  sources: [
    {
      id: 'spacex-starlink',
      title: 'Starlink',
      url: 'https://www.spacex.com/starlink',
      retrievedAt,
      publisher: 'SpaceX',
    },
    {
      id: 'spacex-sl21',
      title: 'Starlink mission',
      url: 'https://www.spacex.com/launches/sl-21',
      retrievedAt,
      publisher: 'SpaceX',
    },
    {
      id: 'fcc-gen2',
      title: 'SpaceX Gen2 Starlink Order and Authorization',
      url: 'https://docs.fcc.gov/public/attachments/DA-26-36A1.pdf',
      retrievedAt,
      publisher: 'Federal Communications Commission',
    },
    {
      id: 'fcc-transition',
      title: 'SpaceX request for orbital deployment and transition operations',
      url: 'https://docs.fcc.gov/public/attachments/DA-24-1193A1.pdf',
      retrievedAt,
      publisher: 'Federal Communications Commission',
    },
    {
      id: 'celestrak-supgp',
      title: 'Supplemental GP Data',
      url: 'https://celestrak.org/NORAD/elements/supplemental/',
      retrievedAt,
      publisher: 'CelesTrak',
    },
  ],
  facts: [
    {
      id: 'constellations-need-repetition',
      text: 'A constellation emerges from repeated deployments into coordinated orbital planes rather than from one launch.',
      sourceIds: ['fcc-gen2'],
    },
    {
      id: 'sixty-satellites',
      text: 'The March 14, 2021 Starlink mission deployed 60 satellites from a Falcon 9 launch.',
      sourceIds: ['spacex-sl21'],
    },
    {
      id: 'transition-orbits',
      text: 'Spacecraft may spend time in deployment and orbit-raising phases before entering an operational shell.',
      sourceIds: ['fcc-transition'],
    },
    {
      id: 'communications-purpose',
      text: 'Starlink is designed as a satellite internet constellation.',
      sourceIds: ['spacex-starlink', 'fcc-gen2'],
    },
    {
      id: 'gp-is-prediction',
      text: 'The scene propagates public general-perturbations element sets; it is not live operator telemetry.',
      sourceIds: ['celestrak-supgp'],
      caveat: 'Propagated locations become less representative as element sets age and after unmodeled maneuvers.',
    },
  ],
  beats: [
    {
      id: 'before-the-shell',
      eyebrow: '01 / THE ORBITAL ENVIRONMENT',
      title: 'Before the shell',
      dateLabel: 'Context view',
      narration: 'Begin with Earth orbit as an environment, not an empty stage. Payloads, rocket bodies, and debris already occupy distinct regimes; the restrained marks preserve that context.',
      factIds: ['constellations-need-repetition'],
      durationMs: 11_000,
      camera: { pitch: 0.26, yaw: 0.38, zoom: 0.62 },
      encoding: 'orbit-regime',
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'deployment-train',
      eyebrow: '02 / FIRST DEPLOYMENT',
      title: 'A train appears',
      dateLabel: 'Representative early cohort',
      narration: 'A compact deployment can look like a bright line of related spacecraft. The line is temporary: it is the beginning of a distributed system, not its final geometry.',
      factIds: ['sixty-satellites'],
      durationMs: 12_000,
      camera: { pitch: 0.08, yaw: 1.1, zoom: 0.39 },
      encoding: 'launch-cohort',
      constellation: 'starlink',
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'orbit-raising',
      eyebrow: '03 / ORBIT RAISING',
      title: 'From deployment to working altitude',
      dateLabel: 'Transition phase',
      narration: 'After separation, spacecraft can spread and raise their orbits. This chapter shows the concept with representative motion; it does not claim an exact historical trajectory for every object.',
      factIds: ['transition-orbits'],
      durationMs: 13_000,
      camera: { pitch: -0.18, yaw: 1.7, zoom: 0.48 },
      encoding: 'data-age',
      constellation: 'starlink',
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'building-planes',
      eyebrow: '04 / BUILDING THE SHELL',
      title: 'Repetition becomes geometry',
      dateLabel: 'Successive launch cohorts',
      narration: 'Repeated launches fill orbital planes. Color now encodes plane density, making the architecture legible without implying that every bright mark is physically that large.',
      factIds: ['constellations-need-repetition'],
      durationMs: 14_000,
      camera: { pitch: 0.44, yaw: 2.35, zoom: 0.67 },
      encoding: 'orbital-plane',
      constellation: 'starlink',
      reconstruction: 'reconstructed',
      scaleMode: 'semantic',
    },
    {
      id: 'present-scale',
      eyebrow: '05 / THE INSTALLED CATALOG',
      title: 'A working system in a shared environment',
      dateLabel: 'Current snapshot',
      narration: 'The final view uses the installed catalog. It can reveal scale, orbital organization, and data age — while coverage, maneuver intent, and operational health require sources beyond this propagated picture.',
      factIds: ['communications-purpose', 'gp-is-prediction'],
      durationMs: 16_000,
      camera: { pitch: 0.34, yaw: 2.9, zoom: 0.73 },
      encoding: 'starlink',
      constellation: 'starlink',
      reconstruction: 'observed',
      scaleMode: 'semantic',
    },
  ],
});
